# Generated by Django 4.0.3 on 2022-03-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rating', models.FloatField()),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
